'org.logicware.DatabaseUser'(sa,'',nil,false,false,nil,nil).

'org.prolobjectlink.db.prolog.PrologDatabaseFunction'(fn,'','dat/relational/test/functions.pl','org.prolobjectlink.db.prolog.PrologArrayList'(4,['X','Y','Z','R'])).

'org.prolobjectlink.db.prolog.PrologDatabaseFunction'(fni,'','dat/relational/test/functions.pl','org.prolobjectlink.db.prolog.PrologArrayList'(4,['X','Y','Z','R'])).

'org.prolobjectlink.db.prolog.PrologDatabaseFunction'(fnj,'','dat/relational/test/functions.pl','org.prolobjectlink.db.prolog.PrologArrayList'(4,['X','Y','Z','R'])).

'org.prolobjectlink.db.prolog.PrologDatabaseFunction'(fnk,'','dat/relational/test/functions.pl','org.prolobjectlink.db.prolog.PrologArrayList'(4,['X','Y','Z','R'])).

'org.prolobjectlink.db.DatabaseClass'('Address','',false,'Address',false,'','org.prolobjectlink.db.prolog.PrologArrayList'(0,'[]'),'org.prolobjectlink.db.prolog.PrologHashMap'(5,[nil,'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(city,'org.prolobjectlink.db.DatabaseField'(city,'',1,'java.lang.String',false,'Address.city',false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(country,'org.prolobjectlink.db.DatabaseField'(country,'',4,'java.lang.String',false,'Address.country',false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(street,'org.prolobjectlink.db.DatabaseField'(street,'',0,'java.lang.String',false,'Address.street',false,false,false,nil,nil,nil,nil,nil)),nil,'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(state,'org.prolobjectlink.db.DatabaseField'(state,'',2,'java.lang.String',false,'Address.state',false,false,false,nil,nil,nil,nil,nil)),nil,nil,nil,'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(zip,'org.prolobjectlink.db.DatabaseField'(zip,'',3,'java.lang.String',false,'Address.zip',false,false,false,nil,nil,nil,nil,nil))])).

'org.prolobjectlink.db.DatabaseClass'('Person','',false,'Person',false,'','org.prolobjectlink.db.prolog.PrologArrayList'(0,'[]'),'org.prolobjectlink.db.prolog.PrologHashMap'(12,['org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(joinDate,'org.prolobjectlink.db.DatabaseField'(joinDate,'',9,'java.util.Date',false,'Person.joinDate',false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(lastLoginDate,'org.prolobjectlink.db.DatabaseField'(lastLoginDate,'',10,'java.util.Date',false,'Person.lastLoginDate',false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(loginCount,'org.prolobjectlink.db.DatabaseField'(loginCount,'',11,'java.lang.Integer',false,'Person.loginCount',false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(birthDate,'org.prolobjectlink.db.DatabaseField'(birthDate,'',8,'java.util.Date',false,'Person.birthDate',false,false,false,nil,nil,nil,nil,nil)),nil,nil,nil,nil,nil,nil,nil,'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(phones,'org.prolobjectlink.db.DatabaseField'(phones,'',5,'java.util.List',false,'Person.phones',false,false,false,'java.lang.String',nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(nickNames,'org.prolobjectlink.db.DatabaseField'(nickNames,'',7,'java.util.Set',false,'Person.nickNames',false,false,false,'java.lang.String',nil,nil,nil,nil)),nil,nil,'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(lastName,'org.prolobjectlink.db.DatabaseField'(lastName,'',3,'java.lang.String',false,'Person.lastName',false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(middleName,'org.prolobjectlink.db.DatabaseField'(middleName,'',2,'java.lang.String',false,'Person.middleName',false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(emails,'org.prolobjectlink.db.DatabaseField'(emails,'',6,'java.util.Collection',false,'Person.emails',false,false,false,'java.lang.String',nil,nil,nil,nil)),nil,'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(firstName,'org.prolobjectlink.db.DatabaseField'(firstName,'',1,'java.lang.String',false,'Person.firstName',false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(address,'org.prolobjectlink.db.DatabaseField'(address,'',4,'org.prolobjectlink.domain.model.Address',false,'Person.address',false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(id,'org.prolobjectlink.db.DatabaseField'(id,'',0,'java.lang.Integer',false,'Person.id',false,true,false,nil,nil,nil,nil,nil)),nil,nil])).

'org.prolobjectlink.db.DatabaseClass'('Employee','',false,'Employee',false,'','org.prolobjectlink.db.prolog.PrologArrayList'(0,'[]'),'org.prolobjectlink.db.prolog.PrologHashMap'(2,[nil,nil,'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(salary,'org.prolobjectlink.db.DatabaseField'(salary,'',0,'java.lang.Long',false,'Employee.salary',false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(department,'org.prolobjectlink.db.DatabaseField'(department,'',1,'org.prolobjectlink.domain.model.Department',false,'Employee.department',false,false,false,nil,nil,nil,nil,nil))])).

'org.prolobjectlink.db.DatabaseClass'('Department','',false,'Department',false,'','org.prolobjectlink.db.prolog.PrologArrayList'(0,'[]'),'org.prolobjectlink.db.prolog.PrologHashMap'(3,[nil,'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(id,'org.prolobjectlink.db.DatabaseField'(id,'',0,'java.lang.Integer',false,'Department.id',false,true,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(employeesByCubicle,'org.prolobjectlink.db.DatabaseField'(employeesByCubicle,'',2,'java.util.Map',false,'Department.employeesByCubicle',false,false,false,'org.prolobjectlink.domain.model.Employee',nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(name,'org.prolobjectlink.db.DatabaseField'(name,'',1,'java.lang.String',false,'Department.name',false,false,false,nil,nil,nil,nil,nil)),nil,nil])).

'org.prolobjectlink.db.DatabaseClass'('Address','',false,'Address',false,'','org.prolobjectlink.db.prolog.PrologArrayList'(0,'[]'),'org.prolobjectlink.db.prolog.PrologHashMap'(5,[nil,'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(city,'org.prolobjectlink.db.DatabaseField'(city,'',1,'java.lang.String',false,'Address.city',false,false,false,false,false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(country,'org.prolobjectlink.db.DatabaseField'(country,'',4,'java.lang.String',false,'Address.country',false,false,false,false,false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(street,'org.prolobjectlink.db.DatabaseField'(street,'',0,'java.lang.String',false,'Address.street',false,false,false,false,false,false,false,nil,nil,nil,nil,nil)),nil,'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(state,'org.prolobjectlink.db.DatabaseField'(state,'',2,'java.lang.String',false,'Address.state',false,false,false,false,false,false,false,nil,nil,nil,nil,nil)),nil,nil,nil,'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(zip,'org.prolobjectlink.db.DatabaseField'(zip,'',3,'java.lang.String',false,'Address.zip',false,false,false,false,false,false,false,nil,nil,nil,nil,nil))])).

'org.prolobjectlink.db.DatabaseClass'('Person','',false,'Person',false,'','org.prolobjectlink.db.prolog.PrologArrayList'(0,'[]'),'org.prolobjectlink.db.prolog.PrologHashMap'(12,['org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(joinDate,'org.prolobjectlink.db.DatabaseField'(joinDate,'',9,'java.util.Date',false,'Person.joinDate',false,false,false,false,false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(lastLoginDate,'org.prolobjectlink.db.DatabaseField'(lastLoginDate,'',10,'java.util.Date',false,'Person.lastLoginDate',false,false,false,false,false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(loginCount,'org.prolobjectlink.db.DatabaseField'(loginCount,'',11,'java.lang.Integer',false,'Person.loginCount',false,false,false,false,false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(birthDate,'org.prolobjectlink.db.DatabaseField'(birthDate,'',8,'java.util.Date',false,'Person.birthDate',false,false,false,false,false,false,false,nil,nil,nil,nil,nil)),nil,nil,nil,nil,nil,nil,nil,'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(phones,'org.prolobjectlink.db.DatabaseField'(phones,'',5,'java.util.List',false,'Person.phones',false,false,false,false,false,false,false,'java.lang.String',nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(nickNames,'org.prolobjectlink.db.DatabaseField'(nickNames,'',7,'java.util.Set',false,'Person.nickNames',false,false,false,false,false,false,false,'java.lang.String',nil,nil,nil,nil)),nil,nil,'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(lastName,'org.prolobjectlink.db.DatabaseField'(lastName,'',3,'java.lang.String',false,'Person.lastName',false,false,false,false,false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(middleName,'org.prolobjectlink.db.DatabaseField'(middleName,'',2,'java.lang.String',false,'Person.middleName',false,false,false,false,false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(emails,'org.prolobjectlink.db.DatabaseField'(emails,'',6,'java.util.Collection',false,'Person.emails',false,false,false,false,false,false,false,'java.lang.String',nil,nil,nil,nil)),nil,'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(firstName,'org.prolobjectlink.db.DatabaseField'(firstName,'',1,'java.lang.String',false,'Person.firstName',false,false,false,false,false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(address,'org.prolobjectlink.db.DatabaseField'(address,'',4,'org.prolobjectlink.domain.model.Address',false,'Person.address',false,false,false,false,false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(id,'org.prolobjectlink.db.DatabaseField'(id,'',0,'java.lang.Integer',false,'Person.id',false,false,false,false,false,true,false,nil,nil,nil,nil,nil)),nil,nil])).

'org.prolobjectlink.db.DatabaseClass'('Employee','',false,'Employee',false,'','org.prolobjectlink.db.prolog.PrologArrayList'(0,'[]'),'org.prolobjectlink.db.prolog.PrologHashMap'(2,[nil,nil,'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(salary,'org.prolobjectlink.db.DatabaseField'(salary,'',0,'java.lang.Long',false,'Employee.salary',false,false,false,false,false,false,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(department,'org.prolobjectlink.db.DatabaseField'(department,'',1,'org.prolobjectlink.domain.model.Department',false,'Employee.department',false,false,false,false,false,false,false,nil,nil,nil,nil,nil))])).

'org.prolobjectlink.db.DatabaseClass'('Department','',false,'Department',false,'','org.prolobjectlink.db.prolog.PrologArrayList'(0,'[]'),'org.prolobjectlink.db.prolog.PrologHashMap'(3,[nil,'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(id,'org.prolobjectlink.db.DatabaseField'(id,'',0,'java.lang.Integer',false,'Department.id',false,false,false,false,false,true,false,nil,nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(employeesByCubicle,'org.prolobjectlink.db.DatabaseField'(employeesByCubicle,'',2,'java.util.Map',false,'Department.employeesByCubicle',false,false,false,false,false,false,false,'org.prolobjectlink.domain.model.Employee',nil,nil,nil,nil)),'org.prolobjectlink.db.prolog.PrologHashMap$HashEntry'(name,'org.prolobjectlink.db.DatabaseField'(name,'',1,'java.lang.String',false,'Department.name',false,false,false,false,false,false,false,nil,nil,nil,nil,nil)),nil,nil])).

'org.prolobjectlink.db.DatabaseUser'('org.prolobjectlink.db.prolog.PrologHashMap'(0,'[]'),'org.prolobjectlink.db.prolog.PrologHashMap'(0,'[]'),sa,'',nil,false,false,nil,nil).

'org.prolobjectlink.db.DatabaseSequence'(adddress_sequence,'',0,'org.prolobjectlink.domain.model.Address',1).

'org.prolobjectlink.db.DatabaseSequence'(person_sequence,'',0,'org.prolobjectlink.domain.model.Person',1).

'org.prolobjectlink.db.DatabaseSequence'(employee_sequence,'',0,'org.prolobjectlink.domain.model.Employee',1).

'org.prolobjectlink.db.DatabaseSequence'(department_sequence,'',0,'org.prolobjectlink.domain.model.Department',1).

'org.logicware.prolog.PrologDatabaseFunction'(fn,'','dat\relational\test\functions.pl','org.logicware.util.ArrayList'(4,['X','Y','Z','R',nil,nil,nil,nil,nil,nil])).

'org.logicware.prolog.PrologDatabaseFunction'(fni,'','dat\relational\test\functions.pl','org.logicware.util.ArrayList'(4,['X','Y','Z','R',nil,nil,nil,nil,nil,nil])).

'org.logicware.prolog.PrologDatabaseFunction'(fnj,'','dat\relational\test\functions.pl','org.logicware.util.ArrayList'(4,['X','Y','Z','R',nil,nil,nil,nil,nil,nil])).

'org.logicware.prolog.PrologDatabaseFunction'(fnk,'','dat\relational\test\functions.pl','org.logicware.util.ArrayList'(4,['X','Y','Z','R',nil,nil,nil,nil,nil,nil])).

'org.logicware.DatabaseClass'('Address','',false,'Address',false,'','org.logicware.util.ArrayList'(0,[nil,nil,nil,nil,nil,nil,nil,nil,nil,nil]),'org.logicware.util.HashMap'(5,[nil,'org.logicware.util.HashMap$HashEntry'(state,'org.logicware.DatabaseField'(state,'',2,'java.lang.String',false,'Address.state',false,false,nil,nil,nil,nil,nil)),'org.logicware.util.HashMap$HashEntry'(zip,'org.logicware.DatabaseField'(zip,'',3,'java.lang.String',false,'Address.zip',false,false,nil,nil,nil,nil,nil)),nil,nil,nil,'org.logicware.util.HashMap$HashEntry'(country,'org.logicware.DatabaseField'(country,'',4,'java.lang.String',false,'Address.country',false,false,nil,nil,nil,nil,nil)),nil,nil,nil,nil,'org.logicware.util.HashMap$HashEntry'(city,'org.logicware.DatabaseField'(city,'',1,'java.lang.String',false,'Address.city',false,false,nil,nil,nil,nil,nil)),nil,'org.logicware.util.HashMap$HashEntry'(street,'org.logicware.DatabaseField'(street,'',0,'java.lang.String',false,'Address.street',false,false,nil,nil,nil,nil,nil)),nil,nil])).

'org.logicware.DatabaseClass'('Person','',false,'Person',false,'','org.logicware.util.ArrayList'(0,[nil,nil,nil,nil,nil,nil,nil,nil,nil,nil]),'org.logicware.util.HashMap'(12,['org.logicware.util.HashMap$HashEntry'(middleName,'org.logicware.DatabaseField'(middleName,'',2,'java.lang.String',false,'Person.middleName',false,false,nil,nil,nil,nil,nil)),'org.logicware.util.HashMap$HashEntry'(lastLoginDate,'org.logicware.DatabaseField'(lastLoginDate,'',10,'java.util.Date',false,'Person.lastLoginDate',false,false,nil,nil,nil,nil,nil)),nil,nil,nil,nil,nil,nil,'org.logicware.util.HashMap$HashEntry'(joinDate,'org.logicware.DatabaseField'(joinDate,'',9,'java.util.Date',false,'Person.joinDate',false,false,nil,nil,nil,nil,nil)),'org.logicware.util.HashMap$HashEntry'(emails,'org.logicware.DatabaseField'(emails,'',6,'java.util.Collection',false,'Person.emails',false,false,'java.lang.String',nil,nil,nil,nil)),nil,nil,'org.logicware.util.HashMap$HashEntry'(address,'org.logicware.DatabaseField'(address,'',4,'org.logicware.domain.model.Address',false,'Person.address',false,false,nil,nil,nil,nil,nil)),nil,nil,nil,nil,nil,nil,'org.logicware.util.HashMap$HashEntry'(birthDate,'org.logicware.DatabaseField'(birthDate,'',8,'java.util.Date',false,'Person.birthDate',false,false,nil,nil,nil,nil,nil)),nil,nil,nil,nil,nil,nil,'org.logicware.util.HashMap$HashEntry'(loginCount,'org.logicware.DatabaseField'(loginCount,'',11,'java.lang.Integer',false,'Person.loginCount',false,false,nil,nil,nil,nil,nil)),'org.logicware.util.HashMap$HashEntry'(nickNames,'org.logicware.DatabaseField'(nickNames,'',7,'java.util.Set',false,'Person.nickNames',false,false,'java.lang.String',nil,nil,nil,nil)),'org.logicware.util.HashMap$HashEntry'(id,'org.logicware.DatabaseField'(id,'',0,'java.lang.Integer',false,'Person.id',true,false,nil,nil,nil,nil,nil)),'org.logicware.util.HashMap$HashEntry'(firstName,'org.logicware.DatabaseField'(firstName,'',1,'java.lang.String',false,'Person.firstName',false,false,nil,nil,nil,nil,nil)),'org.logicware.util.HashMap$HashEntry'(phones,'org.logicware.DatabaseField'(phones,'',5,'java.util.List',false,'Person.phones',false,false,'java.lang.String',nil,nil,nil,nil)),'org.logicware.util.HashMap$HashEntry'(lastName,'org.logicware.DatabaseField'(lastName,'',3,'java.lang.String',false,'Person.lastName',false,false,nil,nil,nil,nil,nil))])).

'org.logicware.DatabaseClass'('Employee','',false,'Employee',false,'','org.logicware.util.ArrayList'(0,[nil,nil,nil,nil,nil,nil,nil,nil,nil,nil]),'org.logicware.util.HashMap'(2,[nil,nil,'org.logicware.util.HashMap$HashEntry'(department,'org.logicware.DatabaseField'(department,'',1,'org.logicware.domain.model.Department',false,'Employee.department',false,false,nil,nil,nil,nil,nil)),nil,nil,nil,'org.logicware.util.HashMap$HashEntry'(salary,'org.logicware.DatabaseField'(salary,'',0,'java.lang.Long',false,'Employee.salary',false,false,nil,nil,nil,nil,nil)),nil,nil,nil,nil,nil,nil,nil,nil,nil])).

'org.logicware.DatabaseClass'('Department','',false,'Department',false,'','org.logicware.util.ArrayList'(0,[nil,nil,nil,nil,nil,nil,nil,nil,nil,nil]),'org.logicware.util.HashMap'(3,[nil,nil,nil,nil,nil,nil,nil,nil,nil,'org.logicware.util.HashMap$HashEntry'(employeesByCubicle,'org.logicware.DatabaseField'(employeesByCubicle,'',2,'java.util.Map',false,'Department.employeesByCubicle',false,false,'org.logicware.domain.model.Employee',nil,nil,nil,nil)),nil,'org.logicware.util.HashMap$HashEntry'(id,'org.logicware.DatabaseField'(id,'',0,'java.lang.Integer',false,'Department.id',true,false,nil,nil,nil,nil,nil)),'org.logicware.util.HashMap$HashEntry'(name,'org.logicware.DatabaseField'(name,'',1,'java.lang.String',false,'Department.name',false,false,nil,nil,nil,nil,nil)),nil,nil,nil])).

'org.logicware.DatabaseSequence'(0,'org.logicware.domain.model.Address',adddress_sequence,1).

'org.logicware.DatabaseSequence'(0,'org.logicware.domain.model.Person',person_sequence,1).

'org.logicware.DatabaseSequence'(0,'org.logicware.domain.model.Employee',employee_sequence,1).

'org.logicware.DatabaseSequence'(0,'org.logicware.domain.model.Department',department_sequence,1).

'org.prolobjectlink.db.prolog.PrologDatabaseView'('org.prolobjectlink.domain.model.view.AnEmployeeView','','dat/relational/test/views.pl','org.prolobjectlink.db.prolog.PrologArrayList'(14,['Salary','Department','Id','FirstName','MiddleName','LastName','Address','Phones','Emails','NickNames','BirthDate','JoinDate','LastLoginDate','LoginCount'])).

'org.prolobjectlink.db.prolog.PrologDatabaseView'('org.prolobjectlink.domain.model.view.AnEmployeeView','','dat/relational/test/views.pl','org.prolobjectlink.db.prolog.PrologArrayList'(17,['$jacocoData','Salary','Department','$jacocoData','Id','FirstName','MiddleName','LastName','Address','Phones','Emails','NickNames','BirthDate','JoinDate','LastLoginDate','LoginCount','$jacocoData'])).

'org.logicware.prolog.PrologDatabaseView'('org.logicware.domain.model.view.AnEmployeeView','','dat\relational\test\views.pl','org.logicware.util.ArrayList'(14,['Salary','Department','Id','FirstName','MiddleName','LastName','Address','Phones','Emails','NickNames','BirthDate','JoinDate','LastLoginDate','LoginCount',nil,nil,nil,nil,nil,nil])).

